// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// API keys are NOT hardcoded here — they are injected at build time via
/// `--dart-define` so they never end up in source control. Example:
///
/// ```sh
/// flutter run --dart-define=FIREBASE_ANDROID_API_KEY=... \
///             --dart-define=FIREBASE_IOS_API_KEY=...
/// ```
///
/// On iOS/Android the native SDKs read their config from
/// GoogleService-Info.plist / google-services.json, so these defines only
/// matter when initializing Firebase with explicit Dart options (e.g. web).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String _androidApiKey =
      String.fromEnvironment('FIREBASE_ANDROID_API_KEY');
  static const String _iosApiKey =
      String.fromEnvironment('FIREBASE_IOS_API_KEY');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:524031929167:android:dee0c4e8793263762df33a',
    messagingSenderId: '524031929167',
    projectId: 'pettogether-76452',
    storageBucket: 'pettogether-76452.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:524031929167:ios:4645c2744a5cbdc62df33a',
    messagingSenderId: '524031929167',
    projectId: 'pettogether-76452',
    storageBucket: 'pettogether-76452.firebasestorage.app',
    iosClientId: '524031929167-e84g4bplu3qcia416q0gla139mcdbbgj.apps.googleusercontent.com',
    iosBundleId: 'com.dreambig.pettogether',
  );
}
